In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('/workspaces/telco_customer_churn_cleaning/notebooks/telco customer churn.csv')

In [3]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
#coneverting the datatype 
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [7]:
import numpy as np

In [8]:
#checking for missing values
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
df[df['TotalCharges'].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [10]:
#since the the customer has not been bille yet the total charges must be 0
df['TotalCharges']= df['TotalCharges'].fillna(0)

In [11]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [ ]:
#checking for duplicates
df.duplicated().sum()

np.int64(0)

In [15]:
# standardizing column names
df.columns= df.columns.str.lower().str.replace(' ','_')

In [17]:
df.head(5)

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [18]:
df["tenure_group"] = pd.cut(
    df["tenure"],
    bins=[0,12,24,48,72],
    labels=["0-12","12-24","24-48","48+"]
)

In [19]:
df["churn_flag"] = df["churn"].map({"Yes":1, "No":0})

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   str
 1   gender            7043 non-null   str
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   str
 4   dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   str
 7   multiplelines     7043 non-null   str
 8   internetservice   7043 non-null   str
 9   onlinesecurity    7043 non-null   str
 10  onlinebackup      7043 non-null   str
 11  deviceprotection  7043 non-null   str
 12  techsupport       7043 non-null   str
 13  streamingtv       7043 non-null   str
 14  streamingmovies   7043 non-null   str
 15  contract          7043 non-null   str
 16  paperlessbilling  7043 non-null   str
 17  paymentmethod     7043 non-null   str
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   str
 21  tenure_group      7032 non-null   category
 22  churn_flag        7043 non-null   int64
dtypes: category(1), float64(2), int64(3), str(17)
memory usage: 1.2 MB

In [23]:
df = df.drop_duplicates()

In [24]:
for col in df.select_dtypes(include="object"):
    print(col, df[col].unique())

customerid <StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
gender <StringArray>
['Female', 'Male']
Length: 2, dtype: str
partner <StringArray>
['Yes', 'No']
Length: 2, dtype: str
dependents <StringArray>
['No', 'Yes']
Length: 2, dtype: str
phoneservice <StringArray>
['No', 'Yes']
Length: 2, dtype: str
multiplelines <StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
internetservice <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
onlinesecurity <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
onlinebackup <StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
deviceprotection <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
techsupport <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streamingtv <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streamingmovies <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
contract <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
paperlessbilling <StringArray>
['Yes', 'No']
Length: 2, dtype: str
paymentmethod <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
churn <StringArray>
['No', 'Yes']
Length: 2, dtype: str

/tmp/ipykernel_14670/1908938104.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object"):

In [26]:
for col in df.select_dtypes(include="string"):
    print(col, df[col].unique())

customerid <StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
gender <StringArray>
['Female', 'Male']
Length: 2, dtype: str
partner <StringArray>
['Yes', 'No']
Length: 2, dtype: str
dependents <StringArray>
['No', 'Yes']
Length: 2, dtype: str
phoneservice <StringArray>
['No', 'Yes']
Length: 2, dtype: str
multiplelines <StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
internetservice <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
onlinesecurity <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
onlinebackup <StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
deviceprotection <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
techsupport <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streamingtv <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streamingmovies <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
contract <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
paperlessbilling <StringArray>
['Yes', 'No']
Length: 2, dtype: str
paymentmethod <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
churn <StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [27]:
df["customerid"].nunique()
df.shape

(7043, 23)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   str
 1   gender            7043 non-null   str
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   str
 4   dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   str
 7   multiplelines     7043 non-null   str
 8   internetservice   7043 non-null   str
 9   onlinesecurity    7043 non-null   str
 10  onlinebackup      7043 non-null   str
 11  deviceprotection  7043 non-null   str
 12  techsupport       7043 non-null   str
 13  streamingtv       7043 non-null   str
 14  streamingmovies   7043 non-null   str
 15  contract          7043 non-null   str
 16  paperlessbilling  7043 non-null   str
 17  paymentmethod     7043 non-null   str
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   float64
 20  churn             7043 non-null   str
 21  tenure_group      7032 non-null   category
 22  churn_flag        7043 non-null   int64
dtypes: category(1), float64(2), int64(3), str(17)
memory usage: 1.2 MB

In [29]:
df.to_csv("telco_cleaned.csv", index=False)